'use strict';

angular.module('productCreate.ctrl', [])
    .controller('productCreateController', ['$scope', '$rootScope', '$http', function ($scope, $rootScope, $http) {

        // Initialize
        $scope.productDetails = {
            userID: '',
            name: '',
            description: '',
            price: '',
            images : [],
            location: '',
            email: '',
            datecreated: Date.now(),
            publishStatus: false
        };

        // Create Product
        $scope.createProduct = function(){
            $http.post(''.url('/api/products/'), $scope.productDetails).success(function(status) {
                $rootScope.$broadcast('onNavigationLinkClicked', 'productList');
            }).error(function(status) {
                console.log('Error - ',status);
            });
        };

        // Mobile Upload
        $scope.imageAdded = [];
        $scope.onAddImage = function(){

            try{
                // Upload image to server
                var upload = function (imageURI, index) {

                    $scope.imageAdded.push({key : 'PLACEHOLDER' + index, value: ''});
                    $scope.$apply();

                    var ft = new FileTransfer(),
                        options = new FileUploadOptions();

                    options.fileKey = "file";
                    options.fileName = 'filename.jpg'; // We will use the name auto-generated by Node at the server side.
                    options.mimeType = "image/jpeg";
                    options.chunkedMode = false;
                    options.params = { // Whatever you populate options.params with, will be available in req.body at the server-side.
                        "description": "Uploaded from my phone"
                    };

                    var c = ft.upload(imageURI, clientAppConfiguration.serverApiBaseURL + "/images",
                        function (res) {
                            console.log('http://localhost:3000/' + res.response);

                            setTimeout(function(index){

                                var imagePlacedInCycle = false;
                                angular.forEach($scope.imageAdded, function(value, key) {
                                    if(value.value === '' && imagePlacedInCycle === false)
                                    {
                                        imagePlacedInCycle = true;
                                        $scope.imageAdded[key].value = 'http://localhost:3000/' + res.response;
                                    }
                                });
                                $scope.$apply();

                            }, 10000);
                        },
                        function (e) {
                            console.log("Upload failed");
                        }, options);
                };

                window.imagePicker.getPictures(
                    function(results) {
                        for (var i = 0; i < results.length; i++) {
                            console.log('Image URI: ' + results[i]);
                            upload(results[i],i);
                        }
                    }, function (error) {
                        console.log('Error: ' + error);
                    });
            }
            catch(e){
                console.log("Error : ", e);
            }
        };

        console.log(" $scope.imageAdded ", $scope.imageAdded );

    }]);