'use strict';

angular.module('productList.ctrl', [])
    .controller('ProductListController', ['$scope', '$rootScope', '$http', function ($scope, $rootScope, $http) {

        $http.get(''.url('/api/products')).success(function(productsCollection) {
            $scope.productsCollection = productsCollection;
        });

        $scope.showProductDetails = function(pageToRedirect, productId){
            $rootScope.$broadcast('onNavigationLinkClicked', pageToRedirect);
            $rootScope.$broadcast('onGetProductDetailsById', productId);
        }

        $scope.imageAdded = ["http://localhost:3000/6c6c4d01-929c-e694-92f4-9abe7cf705bc.jpg"];
        $scope.onAddImage = function(){

            // Upload image to server
            var upload = function (imageURI) {
                var ft = new FileTransfer(),
                    options = new FileUploadOptions();

                options.fileKey = "file";
                options.fileName = 'filename.jpg'; // We will use the name auto-generated by Node at the server side.
                options.mimeType = "image/jpeg";
                options.chunkedMode = false;
                options.params = { // Whatever you populate options.params with, will be available in req.body at the server-side.
                    "description": "Uploaded from my phone"
                };

                var c = ft.upload(imageURI, clientAppConfiguration.serverApiBaseURL + "/images",
                    function (ee) {
                        console.log('http://localhost:3000/' + ee.response);

                        setTimeout(function(){
                            $scope.imageAdded.push('http://localhost:3000/' + ee.response);
                            $scope.$apply();
                        }, 1000);
                    },
                    function (e) {
                        alert("Upload failed");
                    }, options);
            };

            window.imagePicker.getPictures(
                    function(results) {
                        for (var i = 0; i < results.length; i++) {
                            console.log('Image URI: ' + results[i]);
                            upload(results[i]);
                        }
                    }, function (error) {
                        console.log('Error: ' + error);
                });
        }

        console.log(" $scope.imageAdded ", $scope.imageAdded );
    }]);