'use strict';

angular.module('productList.ctrl', [])
    .controller('ProductListController', ['$scope', '$rootScope', '$http', function ($scope, $rootScope, $http) {

        $http.get(''.url('/api/products')).success(function(productsCollection) {
            $scope.productsCollection = productsCollection;
        });

        $scope.showProductDetails = function(pageToRedirect, productId){
            $rootScope.$broadcast('onNavigationLinkClicked', pageToRedirect);
            $rootScope.$broadcast('onGetProductDetailsById', productId);
        }

        $scope.imageAdded = [];
        $scope.onAddImage = function(){

            try{
                // Upload image to server
                var upload = function (imageURI) {

                    $scope.imageAdded.push('PLACEHOLDER');
                    $scope.$apply();

                    var ft = new FileTransfer(),
                        options = new FileUploadOptions();

                    options.fileKey = "file";
                    options.fileName = 'filename.jpg'; // We will use the name auto-generated by Node at the server side.
                    options.mimeType = "image/jpeg";
                    options.chunkedMode = false;
                    options.params = { // Whatever you populate options.params with, will be available in req.body at the server-side.
                        "description": "Uploaded from my phone"
                    };

                    var c = ft.upload(imageURI, clientAppConfiguration.serverApiBaseURL + "/images",
                        function (res) {
                            console.log('http://localhost:3000/' + res.response);

                            setTimeout(function(index){

                                angular.forEach($scope.imageAdded, function(value, key) {

                                    if(value == 'PLACEHOLDER')
                                    {
                                        $scope.imageAdded[key] = 'http://localhost:3000/' + res.response;
                                    }
                                });
                                $scope.$apply();

                                console.log("ImageCollection", angular.stringify($scope.imageAdded));

                            }, 5000);
                        },
                        function (e) {
                            console.log("Upload failed");
                        }, options);
                };

                window.imagePicker.getPictures(
                    function(results) {
                        for (var i = 0; i < results.length; i++) {
                            console.log('Image URI: ' + results[i]);
                            upload(results[i]);
                        }
                    }, function (error) {
                        console.log('Error: ' + error);
                    });
            }
            catch(e){
                console.log("Error : ", e);
            }
        }

        console.log(" $scope.imageAdded ", $scope.imageAdded );
    }]);